apiVersion: apps/v1
kind: Deployment
metadata:
  name: conexao-solidaria-worker
  namespace: conexao-solidaria
spec:
  replicas: 1

  selector:
    matchLabels:
      app: conexao-solidaria-worker

  template:
    metadata:
      labels:
        app: conexao-solidaria-worker

    spec:
      containers:
      - name: worker
        image: christyansouza/conexao-solidaria-worker:latest
        imagePullPolicy: Always

        envFrom:
        - configMapRef:
            name: conexao-solidaria-api-config

        - secretRef:
            name: conexao-solidaria-api-secret