apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: conexao-solidaria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        imagePullPolicy: IfNotPresent

        ports:
        - name: amqp
          containerPort: 5672

        - name: management
          containerPort: 15672

        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: conexao-solidaria-api-secret
              key: RabbitMQ__Username

        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: conexao-solidaria-api-secret
              key: RabbitMQ__Password