name: CI - ConexaoSolidaria

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-api:
    name: Build API
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Restaurar dependências da API
        run: dotnet restore ConexaoSolidaria.API/ConexaoSolidaria.API/ConexaoSolidaria.API.sln

      - name: Compilar API
        run: >
          dotnet build
          ConexaoSolidaria.API/ConexaoSolidaria.API/ConexaoSolidaria.API.sln
          --configuration Release
          --no-restore

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Gerar imagem Docker da API
        uses: docker/build-push-action@v6
        with:
          context: ConexaoSolidaria.API/ConexaoSolidaria.API
          file: ConexaoSolidaria.API/ConexaoSolidaria.API/Dockerfile
          push: false
          load: true
          tags: conexao-solidaria-api:latest

      - name: Verificar imagem Docker da API
        run: |
          docker image inspect conexao-solidaria-api:latest
          docker image ls conexao-solidaria-api

  build-worker:
    name: Build Worker
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Restaurar dependências do Worker
        run: dotnet restore ConexaoSolidaria.Worker/ConexaoSolidaria.Worker.sln

      - name: Compilar Worker
        run: >
          dotnet build
          ConexaoSolidaria.Worker/ConexaoSolidaria.Worker.sln
          --configuration Release
          --no-restore

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Gerar imagem Docker do Worker
        uses: docker/build-push-action@v6
        with:
          context: ConexaoSolidaria.Worker
          file: ConexaoSolidaria.Worker/ConexaoSolidaria.Worker/Dockerfile
          push: false
          load: true
          tags: conexao-solidaria-worker:latest

      - name: Verificar imagem Docker do Worker
        run: |
          docker image inspect conexao-solidaria-worker:latest
          docker image ls conexao-solidaria-worker